name: CI-CD
on:
  push:
    branches:
      - main
    workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Login no DockerHub
        uses: docker/login-action@v3.5.0
        with:
          username: ${{vars.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5.3.0
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            ${{vars.DOCKER_USERNAME}}/github-actions-study:v${{ github.run_number }}
            ${{vars.DOCKER_USERNAME}}/github-actions-study:latest
          
